CREATE TABLE LOT (
  id INT PRIMARY KEY,
  contextId INT,
  vendor INT,
  title VARCHAR(50),
  link VARCHAR(10),
  image VARCHAR(10),
  description VARCHAR(100),
  bid INT,
  bidCount INT,
  reserve INT,
  minimumBid INT,
  price INT,
  currency VARCHAR(10),
  category INT,
  template INT,
  flags INT,
  status INT,
  quantity INT,
  locked INT,
  created DATE,
  lotType INT,
  displayId VARCHAR(10),
  saleCode VARCHAR(10),
  saleId INT
);
