CREATE TABLE LOT (
  id INT PRIMARY KEY AUTO_INCREMENT,
  display_sequence INT NOT NULL,
  vendor INT NOT NULL,
  title VARCHAR(50) NOT NULL,
  link VARCHAR(10) NOT NULL,
  image VARCHAR(10) NOT NULL,
  description VARCHAR(100) NOT NULL,
  bid INT NOT NULL,
  bid_count INT NOT NULL,
  reserve INT NOT NULL,
  minimum_bid INT NOT NULL,
  price INT NOT NULL,
  currency VARCHAR(10) NOT NULL,
  category INT NOT NULL,
  template INT NOT NULL,
  flags INT NOT NULL,
  status INT NOT NULL,
  quantity INT NOT NULL,
  locked INT NOT NULL,
  lot_type INT NOT NULL,
  display_id VARCHAR(10) NOT NULL,
  sale_code VARCHAR(10) NOT NULL,
  sale_id INT NOT NULL
);
